### ISSUE TITLE
As an user, I want to compile the thesis

### ISSUE THREAD

**Issue by JJ** [salvacorts/TFG-Thesis#7]
`listing-golang.sty` is missing.

Either issue instructions in the README.md, or a script to download and compile everything. In this case, you can probably add it to the repo too.

**Comment by JJ** [comment]
Ditto:
```
! LaTeX Error: File `protobuf/lang.sty' not found.
```

**Comment by salvacorts** [comment]
Please, @JJ try now. If it works, close the issue.

**Comment by JJ** [comment]
Works fine. Thanks.
